In [1]:
import numpy as np


In [6]:
######### Q1

def FUNCTIONS(arr):
    last_row = arr[-1]
    AVERAGE = np.mean(last_row)
    MINIMUM = np.min(last_row)
    MAXIMUM = np.max(last_row)
    even=0
    for i in last_row:
        if i%2==0:
            even+=1
    print("Average:", AVERAGE)
    print("Minimum:", MINIMUM)
    print("Maximum:", MAXIMUM)
    print("Number of evens:",even)

arr = np.random.randint(0,60,size=(12, 5))
print("Array:",arr)
    
FUNCTIONS(arr)




Array: [[45 33 16 27 58]
 [50  0  1  5 35]
 [37 49 45 53 18]
 [53 27 12 36 11]
 [29 16  0  6 54]
 [30 50 48 40 55]
 [21 35 51 48 40]
 [51 50  3 25 41]
 [14 10  6  8  4]
 [37 47 22  3 16]
 [ 0 22 50 27  7]
 [43 50 59 49 34]]
Average: 47.0
Minimum: 34
Maximum: 59
Number of evens: 2


In [12]:
############ Q2
A=np.array([[1 ,2 ,3 ],[4 ,5 ,6 ],[7,8,9]])
A[:,::-1]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])